/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ChartBar: typeof import('./components/dashboard/ChartBar.vue')['default']
    ChartPie: typeof import('./components/dashboard/ChartPie.vue')['default']
    ChartTrend: typeof import('./components/dashboard/ChartTrend.vue')['default']
    CommitPanel: typeof import('./components/common/CommitPanel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginModal: typeof import('./components/common/LoginModal.vue')['default']
    MetricCards: typeof import('./components/dashboard/MetricCards.vue')['default']
    NotificationBell: typeof import('./components/common/NotificationBell.vue')['default']
    SearchModal: typeof import('./components/common/SearchModal.vue')['default']
    StatusIndicator: typeof import('./components/widgets/StatusIndicator.vue')['default']
    SummaryCard: typeof import('./components/dashboard/SummaryCard.vue')['default']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
    TimelineCard: typeof import('./components/dashboard/TimelineCard.vue')['default']
    WeatherWidget: typeof import('./components/widgets/WeatherWidget.vue')['default']
  }
}
